language: python
python:
- 2.6
- 2.7
- 3.5
- 3.5-dev
- nightly
install: pip install -r requirements.txt
script:
- py.test
before_script:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
deploy:
  provider: heroku
  api_key:
    secure: udVoBSu7ju+kzVKAb9ViKW7MH/YReRgtQYitFenfcNn1945V9LVa2kNLJh+KJxLnh0zWw2LMaSyjeeUw01F31wIgnxU9PDB7pZjYX9n/kgBshr/7qY16II2VThCOhOSCVSAAWFkbmMA1hP0j3FvyS24Z/P+JukjTZH3QbSfuKti7MDGFDLcJYTL5vj4NE5z4oUPDnPKojV9qBt1H9PK3+8v+kIuV1CMBSNzwbB/sf6Hyk3quQXbygyhwMZ0N3skUifD1MoykMg4TO5Rr5O+Dh4CAW3sLqS4TOYs3OluP5Zp9lVA+f8M3a1Q0z55UpVMNBwV3EbF5keD98HjyLCxf92HqpADrAiZk+J3y34jehJcMGrS2puIK4wfanIfs3FucXdkqQcXPCaRUOH41Ry7/kDEjH4hOjotLiyVzKXMuK0XzHAlv9tuCcJfcTyzg/VHiP8TAzemUi6uzoNJ/RZw49vCvcfT8pNvDuaWtqTyfWYDrk4ityy7m7WopbYZh0MJZXoOPOeXZ/k425rdOIxftb3WJ4FOHN20vDMJZkbLuhHEzrgukbbJbjU/T+IiEtV6D1MEysV2MtpRQ0VBKU4h/e7KvUjxWA8ViTaGIf1Eg9Sql5MMCjS9t9nj71xzNLxvwe3L641A8hSU/GW7DQPIxHl7UvKSZ2Xb5zO/Z7MWMPHM=
  app: sickle-staging
  on:
    repo: simoncopsey/sickle
    python: 2.7